### ISSUE TITLE
Crash when decrypting files on older devices

### ISSUE THREAD

**Issue by albert0m** [benbahrenburg/Securely#22]
I've been having this problem on iPad 2 and 3 with iOS 7.

If I try to decrypt a 20Mb file (not even that large), the system will notify the usual memory warning and after a while the app will crash.
Is there any way to decrypt it in chunks and keep the memory usage low?

**Comment by marconealberto** [comment]
I've been working on decrypting in chunks for the past few days, because I wanted to add a progress bar during the decryption (I changed the algorithm to CFB8 and it takes a little longer than the original algorithm).
The decryption works just fine.
The notification is registered correctly on the proxy and the events are fired.
The only problem is bridging it back to titanium: while the method 'onProgressGlobal' is called correctly at the right time, the titanium events are fired all at the same time only after the decryption has taken place.
I'm not experienced in objective c, would you be able to roughly point me to the problem? My guess is that is something to do with threads or priority on the UI..

Thank you very much


NSData+AES256.m

    for (startByte = 0; startByte <= [fileObject length]; startByte += kChunkSizeBytes) {
        if ((startByte + kChunkSizeBytes) > [fileObject length]) { dataInLength = [fileObject length] - startByte; }
        else { dataInLength = kChunkSizeBytes; }
        
        NSRange bytesRange = NSMakeRange(startByte, (int)dataInLength);
        
        [fileObject getBytes: dataIn range: bytesRange];
        CCCryptorUpdate(cryptor, dataIn, dataInLength, dataOut, bufferLength, &dataOutMoved);
        
        if (dataOutMoved != bufferLength) {
            NSLog(@"dataOutMoved != dataOutLength %zu %zu", dataOutMoved, bufferLength);
        }
        
        [onProgressData setObject:[NSString stringWithFormat:@"%d", startByte] forKey:@"progressData"];
        [onProgressData setObject:[NSString stringWithFormat:@"%d", [fileObject length]] forKey:@"totalData"];
        
         NSInteger progressNumber = (startByte * 100)/[fileObject length];
        

         [[NSNotificationCenter defaultCenter] postNotificationName:@"onProgress" object:onProgressData userInfo:onProgressData];
       
        
        [fileObject replaceBytesInRange: bytesRange withBytes: dataOut];
        
    }



BencodingSecurelyXPlatformCryptoProxy.m


    -(void)readEncrypt:(id)args
    {
    ....
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(onProgressGlobal:) name:@"onProgress" object:nil];
      .... 
       }





     -(void)onProgressGlobal:(NSNotification *)note
     {
          BOOL success = YES;
    
     NSDictionary *theData = [note userInfo];
    if (theData != nil) {
        NSString *progressString = [theData objectForKey:@"progressData"];
        NSString *totalString = [theData objectForKey:@"totalData"];
        
        NSMutableDictionary *event = [NSMutableDictionary dictionaryWithObjectsAndKeys:
                                      NUMBOOL(success),@"success",
                                      nil];
       
        
        
        NSInteger progressNumber = ([progressString intValue] * 100)/[totalString intValue];
        
       
        
        if (previousProgress!=progressNumber) {
             NSLog(@"%d / 100", progressNumber);
            previousProgress = progressNumber;
            
            [event setObject:[NSString stringWithFormat:@"%d", progressNumber] forKey:@"progress"];
            [event setObject:@"100" forKey:@"total"];
            
            [self _fireEventToListener:@"onProgress" withObject:event
                                  listener:onProgressGlobalHandler thisObject:nil];

            
        }
    }
    
    
     }

**Comment by marconealberto** [comment]
I eventually moved the decryption to a different thread.
